### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Leastwise**
Added additional buildings.

### CODE REVIEW

**Comment by brandon-ray** [comment]
We added all of these buildings, I think you forgot to update your fork.

**Comment by Romboter** [comment]
This project moves so fast, I've updated my fork like 4 times in 24hrs and each time I'm about to do a pull request its out of date and what I did is done lol

**Comment by Leastwise** [comment]
lmao, fair enough!

**Comment by brandon-ray** [comment]
Yeah we have been hurrying ever since the it was put on foxholegame.com and it wasn't entirely ready lmao, sorry about that!

**Pull request closed without merging**
